baseURL = 'https:/samwthomas.com/'
languageCode = 'en-us'
title = 'Sam Thomas'
theme = 'smol'
sectionPagesMenu = 'main'

# Parameters
[params]
    subtitle = "Technical engineering and anything which interests me"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "youtube"
        name = "Youtube"
        url = "https://www.youtube.com/channel/UCr527an3LD1BOW1Mq4Vb2Lg"
        weight = 1 

  [[menu.main]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://uk.linkedin.com/in/samuelthomas0"
        weight = 2 